[theme]

# Primary accent for interactive elements
primaryColor = '#eb6d7f'

# Background color for the main content area
backgroundColor = '#004c6c'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#007aaf'

# Color used for almost all text
textColor = '#E6EAE8'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"